version: '3'
services:
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command:
      - --loadmodule /usr/lib/redis/modules/redisearch.so
      - --dir /data
